import { Activity, Download, Send, Printer, LayoutDashboard, History, Settings, LogOut, Building2, User, Calendar, FileText } from 'lucide-react';
import { Button } from '../ui/button';

interface PrescriptionPreviewProps {
  patientName: string;
  onNavigate: (page: string) => void;
  onLogout: () => void;
}

export default function PrescriptionPreview({ patientName, onNavigate, onLogout }: PrescriptionPreviewProps) {
  const prescriptionData = {
    doctor: {
      name: 'Dr. Ahmed Hassan',
      specialty: 'Internal Medicine',
      license: 'MD-45678',
      clinic: 'City Medical Center',
      address: '123 Medical Plaza, Healthcare District',
      phone: '+1 (555) 123-4567',
      email: 'ahmed.hassan@citymedical.com',
    },
    patient: {
      name: patientName || 'Sarah Mitchell',
      age: '32',
      gender: 'Female',
      patientId: 'P-2025-0417',
      date: 'December 17, 2025',
    },
    medications: [
      {
        name: 'Ibuprofen',
        dosage: '400mg',
        frequency: 'Twice daily',
        duration: '7 days',
        instructions: 'Take with food',
      },
      {
        name: 'Magnesium Supplement',
        dosage: '250mg',
        frequency: 'Once daily',
        duration: '30 days',
        instructions: 'Take before bedtime',
      },
    ],
    diagnosis: 'Tension-type headache',
    notes: 'Follow stress management techniques. Maintain regular sleep schedule. Follow-up in 2 weeks.',
  };

  return (
    <div className="min-h-screen bg-[#F9FAFB]">
      {/* Top Navigation */}
      <nav className="bg-white border-b border-gray-200 px-6 py-4">
        <div className="flex items-center justify-between max-w-[1400px] mx-auto">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#2563EB] to-[#14B8A6] flex items-center justify-center">
              <Activity className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-xl font-semibold">MedScribe AI</h1>
              <p className="text-xs text-muted-foreground">Clinical Intelligence Platform</p>
            </div>
          </div>

          <div className="flex items-center gap-6">
            <button
              onClick={() => onNavigate('dashboard')}
              className="flex items-center gap-2 px-4 py-2 rounded-lg hover:bg-gray-100 text-gray-700"
            >
              <LayoutDashboard className="w-4 h-4" />
              <span className="text-sm">Dashboard</span>
            </button>
            <button
              onClick={() => onNavigate('history')}
              className="flex items-center gap-2 px-4 py-2 rounded-lg hover:bg-gray-100 text-gray-700"
            >
              <History className="w-4 h-4" />
              <span className="text-sm">History</span>
            </button>
            <button
              onClick={() => onNavigate('settings')}
              className="flex items-center gap-2 px-4 py-2 rounded-lg hover:bg-gray-100 text-gray-700"
            >
              <Settings className="w-4 h-4" />
              <span className="text-sm">Settings</span>
            </button>
            <div className="h-8 w-px bg-gray-200" />
            <div className="flex items-center gap-3">
              <div className="text-right">
                <p className="text-sm">Dr. Ahmed Hassan</p>
                <p className="text-xs text-muted-foreground">Internal Medicine</p>
              </div>
              <div className="w-10 h-10 rounded-full bg-gradient-to-br from-[#2563EB] to-[#14B8A6] flex items-center justify-center text-white">
                AH
              </div>
            </div>
            <button
              onClick={onLogout}
              className="p-2 rounded-lg hover:bg-gray-100 text-gray-700"
              title="Logout"
            >
              <LogOut className="w-4 h-4" />
            </button>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <div className="max-w-[1000px] mx-auto p-8">
        <div className="space-y-8">
          {/* Page Header */}
          <div className="flex items-center justify-between">
            <div className="space-y-2">
              <h2 className="text-3xl">E-Prescription Generated by MedScribe AI</h2>
              <p className="text-muted-foreground">
                Review and send prescription to patient
              </p>
            </div>
            <div className="flex gap-3">
              <Button
                variant="outline"
                onClick={() => alert('Printing prescription...')}
                className="h-11 px-5 rounded-xl"
              >
                <Printer className="w-4 h-4 mr-2" />
                Print
              </Button>
              <Button
                variant="outline"
                onClick={() => alert('Downloading PDF...')}
                className="h-11 px-5 rounded-xl"
              >
                <Download className="w-4 h-4 mr-2" />
                Download PDF
              </Button>
              <Button
                onClick={() => alert('Prescription sent to patient!')}
                className="h-11 px-5 bg-gradient-to-r from-[#2563EB] to-[#14B8A6] hover:opacity-90"
              >
                <Send className="w-4 h-4 mr-2" />
                Send to Patient
              </Button>
            </div>
          </div>

          {/* Prescription Card */}
          <div className="bg-white rounded-3xl shadow-lg border-2 border-gray-200 overflow-hidden">
            {/* Header with gradient */}
            <div className="bg-gradient-to-r from-[#2563EB] to-[#14B8A6] px-8 py-6 text-white">
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-4">
                  <div className="w-16 h-16 rounded-2xl bg-white/20 backdrop-blur-lg flex items-center justify-center">
                    <Activity className="w-8 h-8" />
                  </div>
                  <div>
                    <h3 className="text-2xl mb-1">MedScribe AI</h3>
                    <p className="text-sm text-white/90">Clinical Intelligence Platform</p>
                  </div>
                </div>
                <div className="text-right text-sm">
                  <p className="mb-1">Prescription ID</p>
                  <p className="text-lg">RX-2025-0417</p>
                </div>
              </div>
            </div>

            {/* Doctor & Patient Info */}
            <div className="grid grid-cols-2 gap-8 px-8 py-6 border-b border-gray-100">
              {/* Doctor Info */}
              <div className="space-y-4">
                <div className="flex items-center gap-2 text-muted-foreground mb-3">
                  <Building2 className="w-4 h-4" />
                  <span className="text-sm">Prescribing Physician</span>
                </div>
                <div className="space-y-2">
                  <p className="text-lg">{prescriptionData.doctor.name}</p>
                  <p className="text-sm text-muted-foreground">{prescriptionData.doctor.specialty}</p>
                  <p className="text-sm text-muted-foreground">License: {prescriptionData.doctor.license}</p>
                  <div className="pt-2 mt-2 border-t border-gray-100">
                    <p className="text-sm">{prescriptionData.doctor.clinic}</p>
                    <p className="text-sm text-muted-foreground">{prescriptionData.doctor.address}</p>
                    <p className="text-sm text-muted-foreground">{prescriptionData.doctor.phone}</p>
                    <p className="text-sm text-muted-foreground">{prescriptionData.doctor.email}</p>
                  </div>
                </div>
              </div>

              {/* Patient Info */}
              <div className="space-y-4">
                <div className="flex items-center gap-2 text-muted-foreground mb-3">
                  <User className="w-4 h-4" />
                  <span className="text-sm">Patient Information</span>
                </div>
                <div className="space-y-2">
                  <p className="text-lg">{prescriptionData.patient.name}</p>
                  <p className="text-sm text-muted-foreground">
                    {prescriptionData.patient.age} years • {prescriptionData.patient.gender}
                  </p>
                  <p className="text-sm text-muted-foreground">Patient ID: {prescriptionData.patient.patientId}</p>
                  <div className="pt-2 mt-2 border-t border-gray-100">
                    <div className="flex items-center gap-2">
                      <Calendar className="w-4 h-4 text-muted-foreground" />
                      <p className="text-sm">{prescriptionData.patient.date}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Diagnosis */}
            <div className="px-8 py-6 bg-blue-50 border-b border-gray-100">
              <div className="flex items-center gap-2 mb-2">
                <FileText className="w-4 h-4 text-[#2563EB]" />
                <span className="text-sm text-[#2563EB]">Diagnosis</span>
              </div>
              <p className="text-lg">{prescriptionData.diagnosis}</p>
            </div>

            {/* Medications Table */}
            <div className="px-8 py-6">
              <h4 className="text-lg mb-4">Prescribed Medications</h4>
              <table className="w-full">
                <thead className="border-b-2 border-gray-200">
                  <tr>
                    <th className="text-left py-3 text-sm text-muted-foreground">Medicine Name</th>
                    <th className="text-left py-3 text-sm text-muted-foreground">Dosage</th>
                    <th className="text-left py-3 text-sm text-muted-foreground">Frequency</th>
                    <th className="text-left py-3 text-sm text-muted-foreground">Duration</th>
                    <th className="text-left py-3 text-sm text-muted-foreground">Instructions</th>
                  </tr>
                </thead>
                <tbody>
                  {prescriptionData.medications.map((med, idx) => (
                    <tr key={idx} className="border-b border-gray-100">
                      <td className="py-4">{med.name}</td>
                      <td className="py-4 text-muted-foreground">{med.dosage}</td>
                      <td className="py-4 text-muted-foreground">{med.frequency}</td>
                      <td className="py-4 text-muted-foreground">{med.duration}</td>
                      <td className="py-4 text-muted-foreground">{med.instructions}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Additional Notes */}
            <div className="px-8 py-6 bg-gray-50 border-t border-gray-100">
              <h4 className="text-sm text-muted-foreground mb-2">Additional Notes</h4>
              <p className="text-sm leading-relaxed">{prescriptionData.notes}</p>
            </div>

            {/* Signature Section */}
            <div className="px-8 py-6 border-t border-gray-100">
              <div className="flex items-end justify-between">
                <div>
                  <div className="h-16 flex items-end">
                    <p className="text-2xl font-signature text-[#2563EB]">Ahmed Hassan</p>
                  </div>
                  <div className="pt-2 border-t border-gray-300 w-64">
                    <p className="text-sm">{prescriptionData.doctor.name}</p>
                    <p className="text-xs text-muted-foreground">{prescriptionData.doctor.specialty}</p>
                  </div>
                </div>
                <div className="text-right text-xs text-muted-foreground">
                  <p>Digital Signature Verified</p>
                  <p>{prescriptionData.patient.date}</p>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="px-8 py-4 bg-gradient-to-r from-[#2563EB]/5 to-[#14B8A6]/5 border-t border-gray-100">
              <div className="flex items-center justify-between text-xs text-muted-foreground">
                <div className="flex items-center gap-2">
                  <Activity className="w-3 h-3 text-[#2563EB]" />
                  <span>Powered by <span className="font-semibold text-[#2563EB]">MedScribe AI</span></span>
                </div>
                <span>HIPAA Compliant • Digitally Verified</span>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center justify-between">
            <Button
              variant="outline"
              onClick={() => onNavigate('notes')}
              className="px-6 h-12 rounded-xl"
            >
              Back to Notes
            </Button>
            <div className="flex gap-4">
              <Button
                variant="outline"
                onClick={() => onNavigate('dashboard')}
                className="px-6 h-12 rounded-xl"
              >
                Back to Dashboard
              </Button>
              <Button
                onClick={() => {
                  alert('Prescription sent to patient!');
                  onNavigate('dashboard');
                }}
                className="px-8 h-12 bg-gradient-to-r from-[#2563EB] to-[#14B8A6] hover:opacity-90"
              >
                <Send className="w-4 h-4 mr-2" />
                Send & Complete
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
